### ISSUE TITLE
server.py fileld to start

### ISSUE THREAD

**Issue by woainiliuying** [mitre-attack/evals_caldera#8]
Service cannot load evals after adding evals plugin，load_data() got an unexpected keyword argument  "directory",please help me,thank you
![QQ图片20200401101617](https://user-images.githubusercontent.com/7877452/78092830-5d769d80-7403-11ea-8981-334f5f502c85.png)

**Comment by recvfrom** [comment]
I ran into this issue as well, trying to use evals_caldera with the latest (2.6.6) caldera release.  It looks like it's a result of breaking API changes since this plugin was written.

This change https://github.com/mitre-attack/evals_caldera/commit/d29352ebb644327104e7f55c046642c13416f077#diff-8bc1f999d73f1bed9d24327079cfe700R8 makes this plugin compatible with 2.4.0 through at last 2.5.0, but once the plugin is loaded it says that the next step after installing sandcat on a machine is to use the [chain ](https://github.com/mitre/chain) plugin, which doesn't appear to be included or updated to work with 2.4.0 and above.  

It looks like rolling back evals_caldera to https://github.com/mitre-attack/evals_caldera/commit/fd21a7aa4fdba7dfde9cf62aca0a32da471fb57e gets it working with caldera 2.3.2

**Comment by jondricek** [comment]
Admin note: closing all remaining issues and pull requests prior to archiving the repository
